# Generated by Django 4.2.14 on 2025-01-17 14:22

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=1)),
                ('locality', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('pin', models.PositiveIntegerField(help_text='Enter six digit code', validators=[app.models.validate_pin_length])),
                ('state', models.CharField(choices=[], max_length=100)),
                ('mobile', models.CharField(help_text='ENter 10 digits', max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('job_city', models.CharField(max_length=50)),
                ('profile_image', models.ImageField(upload_to='profile')),
                ('myfile', models.FileField(blank=True, upload_to='doc')),
            ],
        ),
    ]
